<?php
return [
    [
        'key'        => 'field-service',
        'name'       => 'Service Operation',
        'route'      => 'hws.admin.dashboard.index',
        'sort'       => 1.5,
        'icon-class' => 'field-service-menu-icon',
    ],
    [
        'key'        => 'field-service.dashboard',
        'name'       => 'Dashboard',
        'route'      => 'hws.admin.dashboard.index',
        'sort'       => 1,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.employees',
        'name'       => 'Employees',
        'route'      => 'hws.admin.employees.index',
        'sort'       => 2,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.attendance',
        'name'       => 'Attendance',
        'route'      => 'hws.admin.attendance.index',
        'sort'       => 3,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.service_requests',
        'name'       => 'Service Requests',
        'route'      => 'hws.admin.service-requests.index',
        'sort'       => 4,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.sales_leads',
        'name'       => 'Sales & Leads',
        'route'      => 'hws.admin.sales-leads.index',
        'sort'       => 5,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.inventory',
        'name'       => 'Inventory',
        'route'      => 'hws.admin.inventory.index',
        'sort'       => 6,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.expenses',
        'name'       => 'Expenses',
        'route'      => 'hws.admin.expenses.index',
        'sort'       => 7,
        'icon-class' => '',
    ],
    [
        'key'        => 'field-service.reports',
        'name'       => 'Reports',
        'route'      => 'hws.admin.reports.index',
        'sort'       => 8,
        'icon-class' => '',
    ],
];
